# -*- coding: utf-8 -*-
"""Streamlit App for PBL2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5eZPvAz_zhMjsNvKFq9CisqBfxnJjDj
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.losses import MeanSquaredError
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import os
# Ensure that the required libraries are installed
# !pip install streamlit pandas scikit-learn tensorflow

# Define file paths and constants
SAVE_PATH = "/content/drive/MyDrive/PBL2_files"  # You might need to adjust this path
POLLUTANTS = ['Ozone', 'SO2', 'NO2', 'PM10', 'PM2.5']
SEQ_LENGTH = 3  # Number of days of historical data used for LSTM prediction

# Create the directory if it does not exist
if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)

# Load data function
@st.cache_data
def load_data(file_path):
    """
    Loads the air quality dataset from a CSV file.

    Parameters:
    file_path (str): Path to the CSV file.

    Returns:
    pandas.DataFrame: The loaded dataset, or None if the file does not exist.
    """
    if not os.path.exists(file_path):
        st.error(f"Error: File not found at {file_path}")
        return None
    return pd.read_csv(file_path)

# Preprocess data for LSTM
def preprocess_lstm_data(df, pollutants, seq_length):
    """
    Preprocesses the data for the LSTM model.  This version correctly handles
    the creation of sequences and scaling.

    Args:
        df (pd.DataFrame): The input DataFrame.
        pollutants (list): List of pollutant names.
        seq_length (int): Length of the sequence for LSTM.

    Returns:
        tuple: (X_lstm, y_lstm, scaler_lstm), where
            X_lstm (np.array): Input sequences for LSTM.
            y_lstm (np.array): Target values for LSTM.
            scaler_lstm (MinMaxScaler): Scaler used for normalization.
    """
    data_lstm = df[pollutants].values
    scaler_lstm = MinMaxScaler()
    data_scaled = scaler_lstm.fit_transform(data_lstm)

    X_lstm, y_lstm = [], []
    for i in range(len(data_scaled) - seq_length):
        X_lstm.append(data_scaled[i:i + seq_length])
        y_lstm.append(data_scaled[i + seq_length])

    X_lstm, y_lstm = np.array(X_lstm), np.array(y_lstm)
    return X_lstm, y_lstm, scaler_lstm



# Function to train LSTM model
def train_lstm_model(X_train, y_train, epochs=100, batch_size=32):
    """
    Trains an LSTM model.

    Args:
        X_train (np.array): Training input data.
        y_train (np.array): Training target data.
        epochs (int): Number of training epochs.
        batch_size (int): Batch size for training.

    Returns:
        tensorflow.keras.Model: Trained LSTM model.
    """
    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])))
    model.add(Dense(y_train.shape[1]))
    model.compile(optimizer='adam', loss='mse')
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, verbose=0) # Removed validation_split
    return model

# Function to train Random Forest model
def train_rf_model(X_health, y_health):
    """
    Trains a Random Forest Regressor model.

    Args:
        X_health (pd.DataFrame): Training input data.
        y_health (pd.Series): Training target data.

    Returns:
        sklearn.ensemble.RandomForestRegressor: Trained Random Forest model.
    """
    rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
    rf_model.fit(X_health, y_health)
    return rf_model

# Function to preprocess health data, scale it, and split(Added scaling)
def preprocess_health_data(df, test_size=0.2, random_state=42):
    """
    Preprocesses the data for the Random Forest model.

     Args:
        df (pd.DataFrame): The input DataFrame.
        test_size (float): The proportion of the dataset to include in the test split.
        random_state (int): Controls the shuffling applied to the data before applying the split.

    Returns:
        tuple: A tuple containing the training and testing sets for the features and target variable, and the scaler
    """
    X_health = df[POLLUTANTS]
    y_health = df['AQI']  # Use 'AQI' (assuming this is the health score)

    # Scale the features
    scaler = StandardScaler()
    X_health_scaled = scaler.fit_transform(X_health)
    X_health_scaled = pd.DataFrame(X_health_scaled, columns=X_health.columns) # Convert back to DF

    # Split the data
    X_health_train, X_health_test, y_health_train, y_health_test = train_test_split(
        X_health_scaled, y_health, test_size=test_size, random_state=random_state
    )
    return X_health_train, X_health_test, y_health_train, y_health_test, scaler

# Main function to train models
def train_models(data_file, epochs_lstm=100, batch_size_lstm=32):
    """
    Main function to train the LSTM and Random Forest models.

    Args:
        data_file (str): Path to the CSV data file.
        epochs_lstm (int): Number of epochs for LSTM training.
        batch_size_lstm (int): Batch size for LSTM training.
    """
    df = load_data(data_file)
    if df is None:
        st.error("Failed to load data. Please check the file path.")
        return

    # LSTM Model Training
    st.subheader("LSTM Model Training")
    X_lstm, y_lstm, scaler_lstm = preprocess_lstm_data(df, POLLUTANTS, SEQ_LENGTH)
    X_train_lstm, X_test_lstm, y_train_lstm, y_test_lstm = train_test_split(X_lstm, y_lstm, test_size=0.2, random_state=42) # Added consistent random_state
    lstm_model = train_lstm_model(X_train_lstm, y_train_lstm, epochs_lstm, batch_size_lstm)

    # Evaluate LSTM Model
    y_pred_lstm = lstm_model.predict(X_test_lstm)
    y_pred_lstm_original_scale = scaler_lstm.inverse_transform(y_pred_lstm)
    y_test_lstm_original_scale = scaler_lstm.inverse_transform(y_test_lstm)

    mse_lstm = mean_squared_error(y_test_lstm_original_scale, y_pred_lstm_original_scale)
    r2_lstm = r2_score(y_test_lstm_original_scale, y_pred_lstm_original_scale)
    st.write(f"LSTM Model Evaluation - MSE: {mse_lstm:.2f}, R2 Score: {r2_lstm:.2f}")

    # Save LSTM model and scaler
    lstm_model_path = os.path.join(SAVE_PATH, "trained_lstm_model.h5")
    scaler_lstm_path = os.path.join(SAVE_PATH, "scaler_lstm.pkl")
    lstm_model.save(lstm_model_path)
    joblib.dump(scaler_lstm, scaler_lstm_path)
    st.success(f"LSTM Model Trained & Saved Successfully! at {lstm_model_path} and {scaler_lstm_path}")

    # Random Forest Model Training
    st.subheader("Random Forest Model Training")
    X_health_train, X_health_test, y_health_train, y_health_test, scaler_rf = preprocess_health_data(df) # Added the scaler_rf
    rf_model = train_rf_model(X_health_train, y_health_train)

    # Evaluate Random Forest Model
    y_pred_rf = rf_model.predict(X_health_test)
    mse_rf = mean_squared_error(y_health_test, y_pred_rf)
    r2_rf = r2_score(y_health_test, y_pred_rf)
    st.write(f"Random Forest Model Evaluation - MSE: {mse_rf:.2f}, R2 Score: {r2_rf:.2f}")

    # Save Random Forest model
    rf_model_path = os.path.join(SAVE_PATH, "trained_rf_model.pkl")
    scaler_rf_path = os.path.join(SAVE_PATH, "scaler_rf.pkl")  # Save the scaler
    joblib.dump(rf_model, rf_model_path)
    joblib.dump(scaler_rf, scaler_rf_path) # Save the scaler
    st.success(f"Random Forest Model Trained & Saved Successfully! at {rf_model_path} and {scaler_rf_path}")

# Function to load models
def load_models_for_prediction():
    """Loads the trained LSTM and Random Forest models, and their scalers."""
    try:
        lstm_model_path = os.path.join(SAVE_PATH, "trained_lstm_model.h5")
        rf_model_path = os.path.join(SAVE_PATH, "trained_rf_model.pkl")
        scaler_lstm_path = os.path.join(SAVE_PATH, "scaler_lstm.pkl")
        scaler_rf_path = os.path.join(SAVE_PATH, "scaler_rf.pkl") # Load the scaler

        lstm_model = load_model(lstm_model_path)
        rf_model = joblib.load(rf_model_path)
        scaler_lstm = joblib.load(scaler_lstm_path)
        scaler_rf = joblib.load(scaler_rf_path) # Load the scaler
        return lstm_model, rf_model, scaler_lstm, scaler_rf
    except Exception as e:
        st.error(f"Error loading models: {e}. Please ensure the models are trained and saved.")
        return None, None, None, None

# Function to make predictions and display results
def predict_and_display(lstm_model, rf_model, scaler_lstm, scaler_rf):
    """
    Predicts air quality and health impact based on user input and displays the results.

    Args:
        lstm_model (tensorflow.keras.Model): The trained LSTM model.
        rf_model (sklearn.ensemble.RandomForestRegressor): The trained Random Forest model.
        scaler_lstm (MinMaxScaler): Scaler for LSTM.
        scaler_rf (StandardScaler): Scaler for RF.
    """
    st.header("Air Quality and Health Impact Prediction")
    st.write("Enter pollutant values for the past 3 days:")

    user_input = []
    for day in range(3):
        st.subheader(f"Day {day + 1}")
        day_data = []
        for pollutant in POLLUTANTS:
            val = st.number_input(f"{pollutant}: ", value=30.0, key=f"{pollutant}_{day}")  # Added key
            day_data.append(val)
        user_input.append(day_data)

    user_input = np.array(user_input).reshape(1, 3, 5)

    # Scale the user input using the LSTM scaler
    scaled_input = scaler_lstm.transform(user_input[0])
    scaled_input = scaled_input.reshape(1, 3, 5)

    # Predict future pollutant values using the LSTM model
    future_scaled = lstm_model.predict(scaled_input)
    future_unscaled = scaler_lstm.inverse_transform(future_scaled)

    # Predict health impact score using the Random Forest model
    rf_input = scaler_rf.transform(future_unscaled) # Use the RF scaler
    health_score = rf_model.predict(rf_input)

    st.subheader("📊 Predicted Air Quality for Tomorrow:")
    for i, pol in enumerate(POLLUTANTS):
        st.write(f"{pol}: {future_unscaled[0][i]:.2f}")

    st.subheader("🏥 Predicted Health Impact Score:")
    st.write(f"{health_score[0]:.2f}")

    # Visualize the prediction (optional)
    fig, ax = plt.subplots(figsize=(8, 2))  # Adjust figure size as needed
    ax.text(0.5, 0.5, f'Predicted Health Impact Score: {health_score[0]:.2f}',
            fontsize=12, ha='center', va='center', color='darkred', fontweight='bold')
    ax.axis('off')  # Turn off axis labels and ticks
    st.pyplot(fig)

# Main Streamlit app function
def main():
    """
    Main function to run the Streamlit app.
    """
    st.title("Air Quality and Health Impact Prediction App")

    # Sidebar for user options
    app_mode = st.sidebar.selectbox("Choose an option", ["Train Models", "Predict and Display"])

    if app_mode == "Train Models":
        st.sidebar.subheader("Training Options")
        data_file = st.sidebar.text_input("Path to CSV Data File", "data.csv")  #  "data.csv"
        epochs_lstm = st.sidebar.number_input("LSTM Epochs", value=100, min_value=1)
        batch_size_lstm = st.sidebar.number_input("LSTM Batch Size", value=32, min_value=1)
        if st.sidebar.button("Start Training"):
            train_models(data_file, epochs_lstm, batch_size_lstm)

    elif app_mode == "Predict and Display":
        lstm_model, rf_model, scaler_lstm, scaler_rf = load_models_for_prediction()
        if lstm_model and rf_model and scaler_lstm and scaler_rf:
            predict_and_display(lstm_model, rf_model, scaler_lstm, scaler_rf)
        else:
            st.error("Please train the models first or ensure the model files are in the correct location.")

if __name__ == "__main__":
    main()